### PR TITLE
New approach: Remove Quickform and include form in page.

### PR DESCRIPTION
**Pull request by gngn23**
I removed the Quickform and included the filter form in (as you requested).

It took me a while to come back to this one, so I also had to sync with the changes from #30.

Also:
- removed the JS from the template. Instead I added js/logviewer.js
- added Reset button

Hope that's OK.

### CODE REVIEW

**Comment by adixon** [comment]
Wow, I'm impressed! Your code looks good and I like the little improvements you've done along the way.

I'll try it out for a while on some of my sites first, but I think this is looking close to if not perfect.

Thanks for all your work on this.

**Comment by gngn23** [comment]
Thank you :)

**Comment by gngn23** [comment]
@adixon Did you test it?
Is there anything else I can do?

**Comment by adixon** [comment]
Ah yes, I've been enjoying on my own site and forgot I really should share! Doing that now.

Thanks again!

**Pull request merged**
