### PR TITLE
Support download of log file

### PR DESCRIPTION
**Pull request by twomice**
Large log files can be difficult to read in the browser. A downloaded log file can be parsed, searched, etc, with familiar tools for easier examination. I'd love to have this feature and hope this PR makes it easier to for that to happen.

### CODE REVIEW

**Comment by adixon** [comment]
Scope creep! Awesome idea!

**Comment by twomice** [comment]
Scope creep is always an awesome idea, @adixon !

**Comment by VangelisP** [comment]
Great work and quite handy @twomice , would it be possible to merge this to 2.0 @adixon  ?

**Comment by twomice** [comment]
Thanks @adixon !

**Comment by adixon** [comment]
Yup, in spite of it being a friday afternoon, I couldn't find anything wrong with your code! Thank you!

**Pull request merged**
