### PR TITLE
Add navigation to go prev/next log entry

### PR DESCRIPTION
**Pull request by sluc23**
Add navigation to go prev/next log entry

screenshot_2018-09-04 log entry view dev hosting lspiegel server-dev ixiam lan

### CODE REVIEW

**Comment by adixon** [comment]
Very nice!

**Comment by sluc23** [comment]
thanks @adixon ! 
I haven't changed **info.xml**, so if you think it's ok would be good to have a new release/tag of this extension

**Comment by adixon** [comment]
Yeah, I've got it in testing on my sites, I'll generate a release in a couple of days if no one hits an issue.

The only thing I've noticed so far is perhaps to not show an active link if there is no next/prev (e.g. if you're on the last entry, you still get an active "next" link.) Just a tiny ux thing ...

**Comment by sluc23** [comment]
yeap, I thought the same about hiding the links. Fixed in PR #7

**Pull request merged**
